### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by ghost** [gauravssnl/PyPastebin-Symbian#1]
The title says it all.. sorry but I was looking for such a program for a long time. This is really a failure.

**Comment by gauravssnl** [comment]
what does not work ??Which OS phone are you using ???Explain your problem,please. @koalization

**Comment by ghost** [comment]
Maybe this related to SHA2 (SHA256) issue on Symbian 9.x (S60v3 – S^3), so you need install next update (only work for Symbian S60v5 and above)
* http://dl.nokia.com/ns/symfix/networking_improvements.SIS

Details
* https://answers.microsoft.com/en-us/mobiledevices/forum/mdnokian/sha2-support-on-nikia-c5e71-and-e72/4521fcec-b8e4-4c4a-a5a9-08d1f26118e0?auth=1
* https://answers.microsoft.com/ru-ru/mobiledevices/forum/mdasha/sha2/5ccc1717-4d1c-463e-8051-eec49c596143
